# Generated by Django 3.1.1 on 2020-11-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='mostrarNombre',
        ),
    ]
