# Generated by Django 3.1.1 on 2020-11-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_maxaceptapermisos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='maxAceptaPermisos',
            new_name='maxPermisos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='maxAutPermisos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='maxHomePermisos',
        ),
    ]
