# Generated by Django 3.1.1 on 2020-10-02 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='perEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestionPermisos.estado'),
        ),
    ]
