# Generated by Django 3.1.1 on 2020-10-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0002_auto_20201002_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['-perFechaHora']},
        ),
    ]
