# Generated by Django 3.1.1 on 2020-10-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestionPermisos', '0004_auto_20201006_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableSector',
            fields=[
                ('resUsuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='resUsr', serialize=False, to='auth.user')),
                ('resIdPadre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionPermisos.responsablesector')),
            ],
        ),
        migrations.CreateModel(
            name='SubrogaResponsable',
            fields=[
                ('subId', models.AutoField(primary_key=True, serialize=False)),
                ('subFechaDesde', models.DateField()),
                ('subFechaHasta', models.DateField(blank=True, null=True)),
                ('subResponsableSubroga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionPermisos.responsablesector')),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='secResponsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionPermisos.responsablesector'),
        ),
    ]
