# Generated by Django 3.1.1 on 2020-10-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionPermisos', '0005_auto_20201009_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpleado',
            fields=[
                ('uemId', models.AutoField(primary_key=True, serialize=False)),
                ('uemEmpleado', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='gestionPermisos.empleado')),
                ('uemUsuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
