# Generated by Django 3.1.1 on 2020-10-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0006_usuarioempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablesector',
            name='resIdPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionPermisos.responsablesector'),
        ),
    ]
