# Generated by Django 3.1.1 on 2020-10-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0008_auto_20201009_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablesector',
            name='resSector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resSec', to='gestionPermisos.sector', verbose_name='Sector a Cargo'),
        ),
    ]
