# Generated by Django 3.1.1 on 2020-10-09 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionPermisos', '0009_auto_20201009_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablesector',
            name='resUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resUsr', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable'),
        ),
    ]
