# Generated by Django 3.1.1 on 2020-10-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0010_auto_20201009_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsablesector',
            name='resIdPadre',
        ),
    ]
