# Generated by Django 3.1.1 on 2020-10-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0011_remove_responsablesector_residpadre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subrogaresponsable',
            old_name='subResponsableSubroga',
            new_name='subResSecSubroga',
        ),
    ]
