# Generated by Django 3.1.1 on 2020-10-09 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionPermisos', '0012_auto_20201009_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrogaresponsable',
            name='subUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
            preserve_default=False,
        ),
    ]
