# Generated by Django 3.1.1 on 2020-10-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0013_subrogaresponsable_subusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['legNombre']},
        ),
        migrations.AlterField(
            model_name='subrogaresponsable',
            name='subResSecSubroga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPermisos.responsablesector'),
        ),
    ]
