# Generated by Django 3.1.1 on 2020-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0014_auto_20201022_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='perDescuento96',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
