# Generated by Django 3.1.1 on 2020-10-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0015_auto_20201022_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('ferId', models.AutoField(primary_key=True, serialize=False)),
                ('ferFecha', models.DateField()),
                ('ferDescripcion', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='permiso',
            name='perFechaHora',
            field=models.DateTimeField(),
        ),
    ]
