# Generated by Django 3.1.1 on 2020-10-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0016_auto_20201026_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='ferFecha',
            field=models.DateField(unique=True),
        ),
    ]
