# Generated by Django 3.1.1 on 2020-11-25 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPermisos', '0017_auto_20201026_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='perVistoSolicitante',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 25, 20, 23, 51, 829404), null=True),
        ),
    ]
