# Generated by Django 3.1.1 on 2020-12-10 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionPermisos', '0018_auto_20201125_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('esolId', models.AutoField(primary_key=True, serialize=False)),
                ('esolDescripcion', models.TextField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('tsolId', models.AutoField(primary_key=True, serialize=False)),
                ('tsolDescripcion', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('tsolFormulario', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('tsolActivo', models.BooleanField(blank=True, default=None, null=True)),
                ('tsolRespXMail', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='permiso',
            name='perVistoSolicitante',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 8, 53, 32, 149219), null=True),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solId', models.AutoField(primary_key=True, serialize=False)),
                ('solUsuario', models.TextField(max_length=45)),
                ('solFecha', models.DateTimeField()),
                ('solNotas', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('solFechaleidorrhh', models.DateTimeField(blank=True, default=None, null=True)),
                ('solFechacumplido', models.DateTimeField(blank=True, default=None, null=True)),
                ('solFechaleidousr', models.DateTimeField(blank=True, default=None, null=True)),
                ('solFechaaccionusr', models.DateTimeField(blank=True, default=None, null=True)),
                ('solDescaccionusr', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('solEstado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solEstado', to='gestionPermisos.estadosolicitud')),
                ('solTipoSolicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solTipoSol', to='gestionPermisos.tiposolicitud')),
                ('solUsrcumplido', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solUsrCumplido', to=settings.AUTH_USER_MODEL)),
                ('solUsrleidorrhh', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='solUsrRRHH', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
